let details = [
  {
    "product_button": "NEW ARRIVAL",
    "product-image href": "https://www.mytheresa.com/int_en/givenchy-embellished-crepe-gown-2488225.html?departmentgroup=WOMENSWEAR&catref=category",
    "image": "https://img.mytheresa.com/560/560/33/jpeg/catalog/product/8e/P00768991.jpg",
    "product_name": "Embellished crêpe gown",
    "price": "€ 5,565",
    "availability": "available sizes",
    "available-size": "FR 36XS-S",
    "available-size 2": "FR 38S-M",
    "available-size 3": "FR 40M-L",
    "available-size 4": "FR 42L-XL",
    "available-size 5": "FR 44XL",
    "available-size 6": "FR 46XXL",
    "available-size 7": "FR 483XL",
    "choose-size": "Please choose your size:",
    "available-sizes": "FR 36XS-S",
    "available-sizes 2": "FR 38S-M",
    "available-sizes 3": "FR 40M-L",
    "available-sizes 4": "FR 42L-XL",
    "product-button 2": "",
    "no-sizes": "",
    "available-size 8": "",
    "available-size 9": "",
    "available-size 10": "",
    "available-size 11": "",
    "available-sizes 9": "",
    "available-sizes 10": "",
    "available-sizes 11": "",
    "lazyload src": ""
  },
  {
    "product_button": "NEW ARRIVAL",
    "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-crystal-earrings-2484908.html?departmentgroup=WOMENSWEAR&catref=category",
    "image": "https://img.mytheresa.com/560/560/33/jpeg/catalog/product/50/P00761199.jpg",
    "product_name": "4G crystal earrings",
    "price": "€ 410",
    "availability": "",
    "available-size": "",
    "available-size 2": "",
    "available-size 3": "",
    "available-size 4": "",
    "available-size 5": "",
    "available-size 6": "",
    "available-size 7": "",
    "choose-size": "",
    "available-sizes": "",
    "available-sizes 2": "",
    "available-sizes 3": "",
    "available-sizes 4": "",
    "product-button 2": "NEW SEASON",
    "no-sizes": "product available",
    "available-size 8": "",
    "available-size 9": "",
    "available-size 10": "",
    "available-size 11": "",
    "available-sizes 9": "",
    "available-sizes 10": "",
    "available-sizes 11": "",
    "lazyload src": ""
  },
  {
    "product_button": "NEW ARRIVAL",
    "product-image href": "https://www.mytheresa.com/int_en/givenchy-g-cube-feather-trimmed-leather-sandals-2506002.html?departmentgroup=WOMENSWEAR&catref=category",
    "image": "https://img.mytheresa.com/560/560/33/jpeg/catalog/product/27/P00759210.jpg",
    "product_name": "G Cube feather-trimmed leather sandals",
    "price": "€ 980",
    "availability": "available sizes",
    "available-size": "EU 35",
    "available-size 2": "EU 36",
    "available-size 3": "EU 36.5",
    "available-size 4": "EU 37",
    "available-size 5": "EU 37.5",
    "available-size 6": "EU 38",
    "available-size 7": "EU 38.5",
    "choose-size": "Please choose your size:",
    "available-sizes": "EU 35",
    "available-sizes 2": "EU 36",
    "available-sizes 3": "EU 36.5",
    "available-sizes 4": "EU 37",
    "product-button 2": "NEW SEASON",
    "no-sizes": "",
    "available-size 8": "EU 39",
    "available-size 9": "EU 39.5",
    "available-size 10": "EU 40",
    "available-size 11": "EU 41",
    "available-sizes 9": "EU 39.5",
    "available-sizes 10": "EU 40",
    "available-sizes 11": "EU 41",
    "lazyload src": ""
  },
  {
    "product_button": "NEW ARRIVAL",
    "product-image href": "https://www.mytheresa.com/int_en/givenchy-embellished-off-shoulder-gown-2489243.html?departmentgroup=WOMENSWEAR&catref=category",
    "image": "https://img.mytheresa.com/560/560/33/jpeg/catalog/product/6a/P00771482.jpg",
    "product_name": "Embellished off-shoulder gown",
    "price": "€ 5,565",
    "availability": "available sizes",
    "available-size": "FR 36XS-S",
    "available-size 2": "FR 38S-M",
    "available-size 3": "FR 40M-L",
    "available-size 4": "FR 42L-XL",
    "available-size 5": "FR 44XL",
    "available-size 6": "FR 46XXL",
    "available-size 7": "",
    "choose-size": "Please choose your size:",
    "available-sizes": "FR 36XS-S",
    "available-sizes 2": "FR 38S-M",
    "available-sizes 3": "FR 40M-L",
    "available-sizes 4": "FR 42L-XL",
    "product-button 2": "EXCLUSIVE",
    "no-sizes": "",
    "available-size 8": "",
    "available-size 9": "",
    "available-size 10": "",
    "available-size 11": "",
    "available-sizes 9": "",
    "available-sizes 10": "",
    "available-sizes 11": "",
    "lazyload src": ""
  },
  {
    "product_button": "NEW ARRIVAL",
    "product-image href": "https://www.mytheresa.com/int_en/givenchy-embellished-off-shoulder-gown-2489236.html?departmentgroup=WOMENSWEAR&catref=category",
    "image": "https://img.mytheresa.com/560/560/33/jpeg/catalog/product/5b/P00771481.jpg",
    "product_name": "Embellished off-shoulder gown",
    "price": "€ 5,565",
    "availability": "available sizes",
    "available-size": "FR 36XS-S",
    "available-size 2": "FR 38S-M",
    "available-size 3": "FR 40M-L",
    "available-size 4": "FR 42L-XL",
    "available-size 5": "FR 44XL",
    "available-size 6": "",
    "available-size 7": "",
    "choose-size": "Please choose your size:",
    "available-sizes": "FR 36XS-S",
    "available-sizes 2": "FR 38S-M",
    "available-sizes 3": "FR 40M-L",
    "available-sizes 4": "FR 42L-XL",
    "product-button 2": "EXCLUSIVE",
    "no-sizes": "",
    "available-size 8": "",
    "available-size 9": "",
    "available-size 10": "",
    "available-size 11": "",
    "available-sizes 9": "",
    "available-sizes 10": "",
    "available-sizes 11": "",
    "lazyload src": ""
  },
  {
    "product_button": "NEW ARRIVAL",
    "product-image href": "https://www.mytheresa.com/int_en/givenchy-embellished-crepe-gown-2488225.html?departmentgroup=WOMENSWEAR&catref=category",
    "image": "https://img.mytheresa.com/560/560/33/jpeg/catalog/product/8e/P00768991.jpg",
    "product_name": "Embellished crêpe gown",
    "price": "€ 5,565",
    "availability": "available sizes",
    "available-size": "FR 36XS-S",
    "available-size 2": "FR 38S-M",
    "available-size 3": "FR 40M-L",
    "available-size 4": "FR 42L-XL",
    "available-size 5": "FR 44XL",
    "available-size 6": "FR 46XXL",
    "available-size 7": "FR 483XL",
    "choose-size": "Please choose your size:",
    "available-sizes": "FR 36XS-S",
    "available-sizes 2": "FR 38S-M",
    "available-sizes 3": "FR 40M-L",
    "available-sizes 4": "FR 42L-XL",
    "product-button 2": "",
    "no-sizes": "",
    "available-size 8": "",
    "available-size 9": "",
    "available-size 10": "",
    "available-size 11": "",
    "available-sizes 9": "",
    "available-sizes 10": "",
    "available-sizes 11": "",
    "lazyload src": ""
  },
  {
    "product_button": "NEW ARRIVAL",
    "product-image href": "https://www.mytheresa.com/int_en/givenchy-embellished-crepe-gown-2488225.html?departmentgroup=WOMENSWEAR&catref=category",
    "image": "https://img.mytheresa.com/560/560/33/jpeg/catalog/product/8e/P00768991.jpg",
    "product_name": "Embellished crêpe gown",
    "price": "€ 5,565",
    "availability": "available sizes",
    "available-size": "FR 36XS-S",
    "available-size 2": "FR 38S-M",
    "available-size 3": "FR 40M-L",
    "available-size 4": "FR 42L-XL",
    "available-size 5": "FR 44XL",
    "available-size 6": "FR 46XXL",
    "available-size 7": "FR 483XL",
    "choose-size": "Please choose your size:",
    "available-sizes": "FR 36XS-S",
    "available-sizes 2": "FR 38S-M",
    "available-sizes 3": "FR 40M-L",
    "available-sizes 4": "FR 42L-XL",
    "product-button 2": "",
    "no-sizes": "",
    "available-size 8": "",
    "available-size 9": "",
    "available-size 10": "",
    "available-size 11": "",
    "available-sizes 9": "",
    "available-sizes 10": "",
    "available-sizes 11": "",
    "lazyload src": ""
  },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-g-chain-crepe-gown-2484540.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "https://img.mytheresa.com/560/560/33/jpeg/catalog/product/9a/P00758441.jpg",
  //   "product-name": "G Chain crêpe gown",
  //   "price": "€ 2,065",
  //   "availability": "available sizes",
  //   "available-size": "FR 34XXS",
  //   "available-size 2": "FR 36XS-S",
  //   "available-size 3": "FR 38S-M",
  //   "available-size 4": "FR 40M-L",
  //   "available-size 5": "FR 42L-XL",
  //   "available-size 6": "FR 44XL",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "FR 34XXS",
  //   "available-sizes 2": "FR 36XS-S",
  //   "available-sizes 3": "FR 38S-M",
  //   "available-sizes 4": "FR 40M-L",
  //   "product-button 2": "EXCLUSIVE",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": ""
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-sequined-gown-2489218.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "https://img.mytheresa.com/560/560/33/jpeg/catalog/product/3f/P00758430.jpg",
  //   "product-name": "Sequined gown",
  //   "price": "€ 5,565",
  //   "availability": "available sizes",
  //   "available-size": "FR 34XXS",
  //   "available-size 2": "FR 36XS-S",
  //   "available-size 3": "FR 38S-M",
  //   "available-size 4": "FR 40M-L",
  //   "available-size 5": "FR 42L-XL",
  //   "available-size 6": "FR 44XL",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "FR 34XXS",
  //   "available-sizes 2": "FR 36XS-S",
  //   "available-sizes 3": "FR 38S-M",
  //   "available-sizes 4": "FR 40M-L",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": ""
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-moon-cut-out-mini-leather-shoulder-bag-2467133.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "https://img.mytheresa.com/560/560/33/jpeg/catalog/product/f4/P00761188.jpg",
  //   "product-name": "Moon Cut Out Mini leather shoulder bag",
  //   "price": "€ 1,305",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": ""
  // },
  // {
  //   "product-button": "",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-padlock-chainlink-necklace-2227000.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "https://img.mytheresa.com/560/560/33/jpeg/catalog/product/e2/P00693030.jpg",
  //   "product-name": "4G Padlock chainlink necklace",
  //   "price": "€ 645",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": ""
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-tulle-and-jersey-minidress-2475301.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "4G tulle and jersey minidress",
  //   "price": "€ 1,695",
  //   "availability": "available sizes",
  //   "available-size": "FR 34XXS",
  //   "available-size 2": "FR 36XS-S",
  //   "available-size 3": "FR 38S-M",
  //   "available-size 4": "FR 40M-L",
  //   "available-size 5": "FR 42L-XL",
  //   "available-size 6": "FR 44XL",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "FR 34XXS",
  //   "available-sizes 2": "FR 36XS-S",
  //   "available-sizes 3": "FR 38S-M",
  //   "available-sizes 4": "FR 40M-L",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": ""
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-tulle-and-jersey-midi-dress-2489225.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "https://img.mytheresa.com/560/560/33/jpeg/catalog/product/d4/P00758431.jpg",
  //   "product-name": "4G tulle and jersey midi dress",
  //   "price": "€ 1,910",
  //   "availability": "available sizes",
  //   "available-size": "FR 34XXS",
  //   "available-size 2": "FR 36XS-S",
  //   "available-size 3": "FR 38S-M",
  //   "available-size 4": "FR 40M-L",
  //   "available-size 5": "FR 42L-XL",
  //   "available-size 6": "FR 44XL",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "FR 34XXS",
  //   "available-sizes 2": "FR 36XS-S",
  //   "available-sizes 3": "FR 38S-M",
  //   "available-sizes 4": "FR 40M-L",
  //   "product-button 2": "EXCLUSIVE",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": ""
  // },
  // {
  //   "product-button": "NEW SEASON",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-soft-quilted-crossbody-bag-2486747.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "4G Soft quilted crossbody bag",
  //   "price": "€ 2,020",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": ""
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-g-lock-leather-platform-pumps-2504731.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "https://img.mytheresa.com/560/560/33/jpeg/catalog/product/8f/P00759190.jpg",
  //   "product-name": "G Lock leather platform pumps",
  //   "price": "€ 980",
  //   "availability": "available sizes",
  //   "available-size": "EU 35",
  //   "available-size 2": "EU 36",
  //   "available-size 3": "EU 36.5",
  //   "available-size 4": "EU 37",
  //   "available-size 5": "EU 37.5",
  //   "available-size 6": "EU 38",
  //   "available-size 7": "EU 38.5",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 35",
  //   "available-sizes 2": "EU 36",
  //   "available-sizes 3": "EU 36.5",
  //   "available-sizes 4": "EU 37",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "",
  //   "available-size 8": "EU 39",
  //   "available-size 9": "EU 39.5",
  //   "available-size 10": "EU 40",
  //   "available-size 11": "EU 41",
  //   "available-sizes 9": "EU 39.5",
  //   "available-sizes 10": "EU 40",
  //   "available-sizes 11": "EU 41",
  //   "lazyload src": ""
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-wool-and-mohair-blazer-2498476.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "https://img.mytheresa.com/560/560/33/jpeg/catalog/product/0f/P00771005.jpg",
  //   "product-name": "Wool and mohair blazer",
  //   "price": "€ 2,725",
  //   "availability": "available sizes",
  //   "available-size": "FR 34XXS",
  //   "available-size 2": "FR 36XS-S",
  //   "available-size 3": "FR 38S-M",
  //   "available-size 4": "FR 40M-L",
  //   "available-size 5": "FR 42L-XL",
  //   "available-size 6": "FR 44XL",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "FR 34XXS",
  //   "available-sizes 2": "FR 36XS-S",
  //   "available-sizes 3": "FR 38S-M",
  //   "available-sizes 4": "FR 40M-L",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": ""
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-shark-lock-leather-ankle-boots-2513330.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "https://img.mytheresa.com/560/560/33/jpeg/catalog/product/0c/P00777739.jpg",
  //   "product-name": "Shark Lock leather ankle boots",
  //   "price": "€ 1,855",
  //   "availability": "available sizes",
  //   "available-size": "EU 35",
  //   "available-size 2": "EU 36",
  //   "available-size 3": "EU 37",
  //   "available-size 4": "EU 38",
  //   "available-size 5": "EU 38.5",
  //   "available-size 6": "EU 39",
  //   "available-size 7": "EU 39.5",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 35",
  //   "available-sizes 2": "EU 36",
  //   "available-sizes 3": "EU 37",
  //   "available-sizes 4": "EU 38",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "EU 40",
  //   "available-size 9": "EU 40.5",
  //   "available-size 10": "EU 41",
  //   "available-size 11": "EU 41.5",
  //   "available-sizes 9": "EU 40.5",
  //   "available-sizes 10": "EU 41",
  //   "available-sizes 11": "EU 41.5",
  //   "lazyload src": ""
  // },
  // {
  //   "product-button": "",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-earrings-2091571.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "4G earrings",
  //   "price": "€ 265",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-terra-leather-loafers-2497754.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Terra leather loafers",
  //   "price": "€ 930",
  //   "availability": "available sizes",
  //   "available-size": "EU 35",
  //   "available-size 2": "EU 36",
  //   "available-size 3": "EU 36.5",
  //   "available-size 4": "EU 37",
  //   "available-size 5": "EU 37.5",
  //   "available-size 6": "EU 38",
  //   "available-size 7": "EU 38.5",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 35",
  //   "available-sizes 2": "EU 36",
  //   "available-sizes 3": "EU 36.5",
  //   "available-sizes 4": "EU 37",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "",
  //   "available-size 8": "EU 39",
  //   "available-size 9": "EU 39.5",
  //   "available-size 10": "EU 40",
  //   "available-size 11": "EU 41",
  //   "available-sizes 9": "EU 39.5",
  //   "available-sizes 10": "EU 40",
  //   "available-sizes 11": "EU 41",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW SEASON",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-antigona-stretch-mini-leather-crossbody-bag-2475344.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Antigona Stretch Mini leather crossbody bag",
  //   "price": "€ 1,585",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW SEASON",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-small-quilted-leather-shoulder-bag-2467454.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "4G Small quilted leather shoulder bag",
  //   "price": "€ 2,020",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-jersey-and-tulle-bodysuit-2498915.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "4G jersey and tulle bodysuit",
  //   "price": "€ 790",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "XS",
  //   "available-sizes 2": "S",
  //   "available-sizes 3": "M",
  //   "available-sizes 4": "L",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "sold out",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-shark-lock-leather-knee-high-boots-2456182.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Shark Lock wide-fit leather knee-high boots",
  //   "price": "€ 2,070",
  //   "availability": "available sizes",
  //   "available-size": "EU 36",
  //   "available-size 2": "EU 37",
  //   "available-size 3": "EU 38",
  //   "available-size 4": "EU 39",
  //   "available-size 5": "EU 40",
  //   "available-size 6": "EU 41",
  //   "available-size 7": "EU 42",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 36",
  //   "available-sizes 2": "EU 37",
  //   "available-sizes 3": "EU 38",
  //   "available-sizes 4": "EU 39",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "EU 43",
  //   "available-size 9": "EU 44EU 44",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "EU 44EU 44",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "EXCLUSIVE",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-shark-lock-leather-knee-high-boots-2334138.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Shark Lock leather knee-high boots",
  //   "price": "€ 2,070",
  //   "availability": "available sizes",
  //   "available-size": "EU 35",
  //   "available-size 2": "EU 35.5",
  //   "available-size 3": "EU 36",
  //   "available-size 4": "EU 36.5",
  //   "available-size 5": "EU 37",
  //   "available-size 6": "EU 37.5",
  //   "available-size 7": "EU 38",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 35",
  //   "available-sizes 2": "EU 35.5",
  //   "available-sizes 3": "EU 36",
  //   "available-sizes 4": "EU 36.5",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "EU 38.5",
  //   "available-size 9": "EU 39",
  //   "available-size 10": "EU 39.5",
  //   "available-size 11": "EU 40",
  //   "available-sizes 9": "EU 39",
  //   "available-sizes 10": "EU 39.5",
  //   "available-sizes 11": "EU 40",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-leather-biker-jacket-2514278.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Leather biker jacket",
  //   "price": "€ 3,380",
  //   "availability": "available sizes",
  //   "available-size": "FR 34XXS",
  //   "available-size 2": "FR 36XS-S",
  //   "available-size 3": "FR 38S-M",
  //   "available-size 4": "FR 40M-L",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "FR 34XXS",
  //   "available-sizes 2": "FR 36XS-S",
  //   "available-sizes 3": "FR 38S-M",
  //   "available-sizes 4": "FR 40M-L",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-mini-leather-shoulder-bag-2467450.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "4G Mini leather shoulder bag",
  //   "price": "€ 1,585",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW SEASON",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-g-cube-leather-knee-high-boots-2467554.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "G Cube leather knee-high boots",
  //   "price": "€ 1,585",
  //   "availability": "available sizes",
  //   "available-size": "EU 35",
  //   "available-size 2": "EU 36",
  //   "available-size 3": "EU 36.5",
  //   "available-size 4": "EU 37",
  //   "available-size 5": "EU 37.5",
  //   "available-size 6": "EU 38",
  //   "available-size 7": "EU 38.5",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 35",
  //   "available-sizes 2": "EU 36",
  //   "available-sizes 3": "EU 36.5",
  //   "available-sizes 4": "EU 37",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "EU 39",
  //   "available-size 9": "EU 39.5",
  //   "available-size 10": "EU 40",
  //   "available-size 11": "EU 41",
  //   "available-sizes 9": "EU 39.5",
  //   "available-sizes 10": "EU 40",
  //   "available-sizes 11": "EU 41",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-belted-wool-and-silk-coat-2505217.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Belted wool and silk coat",
  //   "price": "€ 3,005",
  //   "availability": "available sizes",
  //   "available-size": "FR 34XXS",
  //   "available-size 2": "FR 36XS-S",
  //   "available-size 3": "FR 38S-M",
  //   "available-size 4": "FR 40M-L",
  //   "available-size 5": "FR 42L-XL",
  //   "available-size 6": "FR 44XL",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "FR 34XXS",
  //   "available-sizes 2": "FR 36XS-S",
  //   "available-sizes 3": "FR 38S-M",
  //   "available-sizes 4": "FR 40M-L",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-embroidered-medium-canvas-tote-2459039.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "4G embroidered Medium canvas tote",
  //   "price": "€ 2,240",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-wedge-leather-ankle-boots-2504743.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Wedge leather ankle boots",
  //   "price": "€ 1,475",
  //   "availability": "available sizes",
  //   "available-size": "EU 35",
  //   "available-size 2": "EU 36",
  //   "available-size 3": "EU 36.5",
  //   "available-size 4": "EU 37",
  //   "available-size 5": "EU 37.5",
  //   "available-size 6": "EU 38",
  //   "available-size 7": "EU 38.5",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 35",
  //   "available-sizes 2": "EU 36",
  //   "available-sizes 3": "EU 36.5",
  //   "available-sizes 4": "EU 37",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "",
  //   "available-size 8": "EU 39",
  //   "available-size 9": "EU 39.5",
  //   "available-size 10": "EU 40",
  //   "available-size 11": "EU 41",
  //   "available-sizes 9": "EU 39.5",
  //   "available-sizes 10": "EU 40",
  //   "available-sizes 11": "EU 41",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-giv-cut-sunglasses-2515312.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Giv Cut sunglasses",
  //   "price": "€ 379",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-wool-cashmere-and-silk-coat-2276049.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Wool, cashmere and silk coat",
  //   "price": "€ 3,330",
  //   "availability": "available sizes",
  //   "available-size": "FR 34XXS",
  //   "available-size 2": "FR 36XS-S",
  //   "available-size 3": "FR 38S-M",
  //   "available-size 4": "FR 40M-L",
  //   "available-size 5": "FR 42L-XL",
  //   "available-size 6": "FR 44XL",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "FR 34XXS",
  //   "available-sizes 2": "FR 36XS-S",
  //   "available-sizes 3": "FR 38S-M",
  //   "available-sizes 4": "FR 40M-L",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-g-lock-leather-wedge-knee-high-boots-2504754.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "G-Lock leather wedge knee-high boots",
  //   "price": "€ 1,805",
  //   "availability": "available sizes",
  //   "available-size": "EU 35",
  //   "available-size 2": "EU 36",
  //   "available-size 3": "EU 36.5",
  //   "available-size 4": "EU 37",
  //   "available-size 5": "EU 37.5",
  //   "available-size 6": "EU 38",
  //   "available-size 7": "EU 38.5",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 35",
  //   "available-sizes 2": "EU 36",
  //   "available-sizes 3": "EU 36.5",
  //   "available-sizes 4": "EU 37",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "",
  //   "available-size 8": "EU 39",
  //   "available-size 9": "EU 40",
  //   "available-size 10": "EU 41",
  //   "available-size 11": "",
  //   "available-sizes 9": "EU 40",
  //   "available-sizes 10": "EU 41",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-shark-lock-leather-knee-high-boots-2513553.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Shark Lock leather knee-high boots",
  //   "price": "€ 2,070",
  //   "availability": "available sizes",
  //   "available-size": "EU 35",
  //   "available-size 2": "EU 36",
  //   "available-size 3": "EU 37",
  //   "available-size 4": "EU 38",
  //   "available-size 5": "EU 38.5",
  //   "available-size 6": "EU 39",
  //   "available-size 7": "EU 39.5",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 35",
  //   "available-sizes 2": "EU 36",
  //   "available-sizes 3": "EU 37",
  //   "available-sizes 4": "EU 38",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "EU 40",
  //   "available-size 9": "EU 40.5",
  //   "available-size 10": "EU 41",
  //   "available-size 11": "EU 41.5",
  //   "available-sizes 9": "EU 40.5",
  //   "available-sizes 10": "EU 41",
  //   "available-sizes 11": "EU 41.5",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-logo-cotton-jersey-hoodie-2505165.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Logo cotton jersey hoodie",
  //   "price": "€ 900",
  //   "availability": "available sizes",
  //   "available-size": "XS",
  //   "available-size 2": "S",
  //   "available-size 3": "M",
  //   "available-size 4": "L",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "XS",
  //   "available-sizes 2": "S",
  //   "available-sizes 3": "M",
  //   "available-sizes 4": "L",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-g-mini-printed-denim-tote-bag-2502844.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "G Mini printed denim tote bag",
  //   "price": "€ 1,410",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW SEASON",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-low-top-sneakers-2467568.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "G4 leather low-top sneakers",
  //   "price": "€ 650",
  //   "availability": "available sizes",
  //   "available-size": "EU 35",
  //   "available-size 2": "EU 35.5",
  //   "available-size 3": "EU 36",
  //   "available-size 4": "EU 36.5",
  //   "available-size 5": "EU 37",
  //   "available-size 6": "EU 37.5",
  //   "available-size 7": "EU 38",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 35",
  //   "available-sizes 2": "EU 35.5",
  //   "available-sizes 3": "EU 36",
  //   "available-sizes 4": "EU 36.5",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "EU 38.5",
  //   "available-size 9": "EU 39",
  //   "available-size 10": "EU 39.5",
  //   "available-size 11": "EU 40",
  //   "available-sizes 9": "EU 39",
  //   "available-sizes 10": "EU 39.5",
  //   "available-sizes 11": "EU 40",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-distressed-mid-rise-wide-leg-jeans-2388785.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Distressed mid-rise wide-leg jeans",
  //   "price": "€ 885",
  //   "availability": "available sizes",
  //   "available-size": "25",
  //   "available-size 2": "26",
  //   "available-size 3": "27",
  //   "available-size 4": "28",
  //   "available-size 5": "29",
  //   "available-size 6": "30",
  //   "available-size 7": "31",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "25",
  //   "available-sizes 2": "26",
  //   "available-sizes 3": "27",
  //   "available-sizes 4": "28",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW SEASON",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-logo-cotton-t-shirt-2484400.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Logo cotton T-shirt",
  //   "price": "€ 460",
  //   "availability": "available sizes",
  //   "available-size": "XS",
  //   "available-size 2": "S",
  //   "available-size 3": "M",
  //   "available-size 4": "L",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "XS",
  //   "available-sizes 2": "S",
  //   "available-sizes 3": "M",
  //   "available-sizes 4": "L",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-g-hobo-leather-shoulder-bag-2408473.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "G-Hobo Mini leather shoulder bag",
  //   "price": "€ 1,585",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW SEASON",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-g4-leather-low-top-sneakers-2484906.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "G4 leather low-top sneakers",
  //   "price": "€ 650",
  //   "availability": "available sizes",
  //   "available-size": "EU 35",
  //   "available-size 2": "EU 35.5",
  //   "available-size 3": "EU 36",
  //   "available-size 4": "EU 36.5",
  //   "available-size 5": "EU 37",
  //   "available-size 6": "EU 37.5",
  //   "available-size 7": "EU 38",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 35",
  //   "available-sizes 2": "EU 35.5",
  //   "available-sizes 3": "EU 36",
  //   "available-sizes 4": "EU 36.5",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "EU 38.5",
  //   "available-size 9": "EU 39",
  //   "available-size 10": "EU 39.5",
  //   "available-size 11": "EU 40",
  //   "available-sizes 9": "EU 39",
  //   "available-sizes 10": "EU 39.5",
  //   "available-sizes 11": "EU 40",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW SEASON",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-moon-cut-out-mini-leather-shoulder-bag-2467448.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Moon Cut Out Mini leather shoulder bag",
  //   "price": "€ 1,085",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-g-mini-canvas-tote-bag-2506006.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "G Mini canvas tote bag",
  //   "price": "€ 1,085",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-x-bstroy-printed-jersey-crop-top-2505047.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "x Bstroy printed jersey crop top",
  //   "price": "€ 415",
  //   "availability": "available sizes",
  //   "available-size": "XS",
  //   "available-size 2": "S",
  //   "available-size 3": "M",
  //   "available-size 4": "L",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "XS",
  //   "available-sizes 2": "S",
  //   "available-sizes 3": "M",
  //   "available-sizes 4": "L",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-jacquard-mockneck-sweater-2498494.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "4G jacquard mockneck sweater",
  //   "price": "€ 960",
  //   "availability": "available sizes",
  //   "available-size": "XS",
  //   "available-size 2": "S",
  //   "available-size 3": "M",
  //   "available-size 4": "L",
  //   "available-size 5": "XL",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "XS",
  //   "available-sizes 2": "S",
  //   "available-sizes 3": "M",
  //   "available-sizes 4": "L",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-reversible-leather-belt-2498644.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "4G reversible leather belt",
  //   "price": "€ 325",
  //   "availability": "available sizes",
  //   "available-size": "65CM",
  //   "available-size 2": "70CM",
  //   "available-size 3": "75CM",
  //   "available-size 4": "80CM",
  //   "available-size 5": "85CM",
  //   "available-size 6": "90CM",
  //   "available-size 7": "95CM",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "65CM",
  //   "available-sizes 2": "70CM",
  //   "available-sizes 3": "75CM",
  //   "available-sizes 4": "80CM",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW SEASON",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-g-hobo-medium-leather-shoulder-bag-2467135.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "G-Hobo Medium leather shoulder bag",
  //   "price": "€ 2,175",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-cutout-slim-pants-2351369.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Cutout slim pants",
  //   "price": "€ 749",
  //   "availability": "available sizes",
  //   "available-size": "FR 34XXS",
  //   "available-size 2": "FR 36XS-S",
  //   "available-size 3": "FR 38S-M",
  //   "available-size 4": "FR 40M-L",
  //   "available-size 5": "FR 42L-XL",
  //   "available-size 6": "FR 44XL",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "FR 34XXS",
  //   "available-sizes 2": "FR 36XS-S",
  //   "available-sizes 3": "FR 38S-M",
  //   "available-sizes 4": "FR 40M-L",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW SEASON",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-square-acetate-sunglasses-2429486.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "4G square acetate sunglasses",
  //   "price": "€ 155",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-g-cube-leather-ankle-boots-2467579.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "G Cube leather ankle boots",
  //   "price": "€ 1,195",
  //   "availability": "available sizes",
  //   "available-size": "EU 35",
  //   "available-size 2": "EU 36",
  //   "available-size 3": "EU 36.5",
  //   "available-size 4": "EU 37",
  //   "available-size 5": "EU 37.5",
  //   "available-size 6": "EU 38",
  //   "available-size 7": "EU 38.5",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 35",
  //   "available-sizes 2": "EU 36",
  //   "available-sizes 3": "EU 36.5",
  //   "available-sizes 4": "EU 37",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "",
  //   "available-size 8": "EU 39",
  //   "available-size 9": "EU 39.5",
  //   "available-size 10": "EU 40",
  //   "available-size 11": "EU 41",
  //   "available-sizes 9": "EU 40",
  //   "available-sizes 10": "EU 41",
  //   "available-sizes 11": "EU 39.5",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-terra-leather-knee-high-boots-2431751.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Terra leather knee-high boots",
  //   "price": "€ 1,135",
  //   "availability": "available sizes",
  //   "available-size": "EU 35",
  //   "available-size 2": "EU 36",
  //   "available-size 3": "EU 36.5",
  //   "available-size 4": "EU 37",
  //   "available-size 5": "EU 37.5",
  //   "available-size 6": "EU 38",
  //   "available-size 7": "EU 38.5",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 35",
  //   "available-sizes 2": "EU 36",
  //   "available-sizes 3": "EU 36.5",
  //   "available-sizes 4": "EU 37",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "EU 39",
  //   "available-size 9": "EU 39.5",
  //   "available-size 10": "EU 40",
  //   "available-size 11": "EU 40.5",
  //   "available-sizes 9": "EU 39.5",
  //   "available-sizes 10": "EU 40",
  //   "available-sizes 11": "EU 40.5",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-short-sleeved-jacquard-sweater-2498508.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "4G short-sleeved jacquard sweater",
  //   "price": "€ 790",
  //   "availability": "available sizes",
  //   "available-size": "XS",
  //   "available-size 2": "S",
  //   "available-size 3": "M",
  //   "available-size 4": "L",
  //   "available-size 5": "XL",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "XS",
  //   "available-sizes 2": "S",
  //   "available-sizes 3": "M",
  //   "available-sizes 4": "L",
  //   "product-button 2": "NEW SEASON",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-leopard-print-jacquard-wool-coat-2464106.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Leopard-print jacquard wool coat",
  //   "price": "€ 3,185",
  //   "availability": "available sizes",
  //   "available-size": "FR 34XXS",
  //   "available-size 2": "FR 36XS-S",
  //   "available-size 3": "FR 38S-M",
  //   "available-size 4": "FR 40M-L",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "FR 34XXS",
  //   "available-sizes 2": "FR 36XS-S",
  //   "available-sizes 3": "FR 38S-M",
  //   "available-sizes 4": "FR 40M-L",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-g-chain-ring-2498461.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "G Chain ring",
  //   "price": "€ 300",
  //   "availability": "available sizes",
  //   "available-size": "50MM",
  //   "available-size 2": "52MM",
  //   "available-size 3": "54MM",
  //   "available-size 4": "56MM",
  //   "available-size 5": "58MM",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "50MM",
  //   "available-sizes 2": "52MM",
  //   "available-sizes 3": "54MM",
  //   "available-sizes 4": "56MM",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW SEASON",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-lavaliere-silk-blouse-2488148.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Lavaliere silk-blend blouse",
  //   "price": "€ 1,805",
  //   "availability": "available sizes",
  //   "available-size": "FR 34XXS",
  //   "available-size 2": "FR 36XS-S",
  //   "available-size 3": "FR 38S-M",
  //   "available-size 4": "FR 40M-L",
  //   "available-size 5": "FR 42L-XL",
  //   "available-size 6": "FR 44XL",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "FR 34XXS",
  //   "available-sizes 2": "FR 36XS-S",
  //   "available-sizes 3": "FR 38S-M",
  //   "available-sizes 4": "FR 40M-L",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-shark-lock-leather-knee-high-boots-2334152.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Shark Lock leather knee-high boots",
  //   "price": "€ 2,070",
  //   "availability": "available sizes",
  //   "available-size": "EU 35",
  //   "available-size 2": "EU 35.5",
  //   "available-size 3": "EU 36",
  //   "available-size 4": "EU 36.5",
  //   "available-size 5": "EU 37",
  //   "available-size 6": "EU 37.5",
  //   "available-size 7": "EU 38",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 35",
  //   "available-sizes 2": "EU 35.5",
  //   "available-sizes 3": "EU 36",
  //   "available-sizes 4": "EU 36.5",
  //   "product-button 2": "EXCLUSIVE",
  //   "no-sizes": "",
  //   "available-size 8": "EU 38.5",
  //   "available-size 9": "EU 39",
  //   "available-size 10": "EU 39.5",
  //   "available-size 11": "EU 40",
  //   "available-sizes 9": "EU 39",
  //   "available-sizes 10": "EU 39.5",
  //   "available-sizes 11": "EU 40",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-shark-lock-suede-ankle-boots-2512735.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Shark Lock suede ankle boots",
  //   "price": "€ 1,960",
  //   "availability": "available sizes",
  //   "available-size": "EU 35",
  //   "available-size 2": "EU 35.5",
  //   "available-size 3": "EU 36",
  //   "available-size 4": "EU 36.5",
  //   "available-size 5": "EU 37",
  //   "available-size 6": "EU 37.5",
  //   "available-size 7": "EU 38",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 35",
  //   "available-sizes 2": "EU 35.5",
  //   "available-sizes 3": "EU 36",
  //   "available-sizes 4": "EU 36.5",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "EU 38.5",
  //   "available-size 9": "EU 39",
  //   "available-size 10": "EU 39.5",
  //   "available-size 11": "EU 40",
  //   "available-sizes 9": "EU 39",
  //   "available-sizes 10": "EU 39.5",
  //   "available-sizes 11": "EU 40",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW SEASON",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-4g-mini-leather-shoulder-bag-2467137.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "4G Mini leather shoulder bag",
  //   "price": "€ 1,585",
  //   "availability": "",
  //   "available-size": "",
  //   "available-size 2": "",
  //   "available-size 3": "",
  //   "available-size 4": "",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "",
  //   "available-sizes": "",
  //   "available-sizes 2": "",
  //   "available-sizes 3": "",
  //   "available-sizes 4": "",
  //   "product-button 2": "",
  //   "no-sizes": "product available",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-single-breasted-coat-2355911.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Single-breasted coat",
  //   "price": "€ 2,095",
  //   "availability": "available sizes",
  //   "available-size": "FR 34XXS",
  //   "available-size 2": "FR 36XS-S",
  //   "available-size 3": "FR 38S-M",
  //   "available-size 4": "FR 40M-L",
  //   "available-size 5": "FR 42L-XL",
  //   "available-size 6": "FR 44XL",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "FR 34XXS",
  //   "available-sizes 2": "FR 36XS-S",
  //   "available-sizes 3": "FR 38S-M",
  //   "available-sizes 4": "FR 40M-L",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "NEW ARRIVAL",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-shark-lock-leather-ankle-boots-2513339.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Shark Lock leather ankle boots",
  //   "price": "€ 1,855",
  //   "availability": "available sizes",
  //   "available-size": "EU 36",
  //   "available-size 2": "EU 37",
  //   "available-size 3": "EU 39",
  //   "available-size 4": "EU 39.5",
  //   "available-size 5": "EU 40.5",
  //   "available-size 6": "EU 41",
  //   "available-size 7": "EU 41.5",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "EU 36",
  //   "available-sizes 2": "EU 37",
  //   "available-sizes 3": "EU 39",
  //   "available-sizes 4": "EU 39.5",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "EU 42",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-g-chain-ring-2032016.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "G Chain ring",
  //   "price": "€ 300",
  //   "availability": "available sizes",
  //   "available-size": "50MM",
  //   "available-size 2": "52MM",
  //   "available-size 3": "54MM",
  //   "available-size 4": "56MM",
  //   "available-size 5": "",
  //   "available-size 6": "",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "50MM",
  //   "available-sizes 2": "52MM",
  //   "available-sizes 3": "54MM",
  //   "available-sizes 4": "56MM",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // },
  // {
  //   "product-button": "",
  //   "product-image href": "https://www.mytheresa.com/int_en/givenchy-satin-gown-2382876.html?departmentgroup=WOMENSWEAR&catref=category",
  //   "ls-is-cached src": "",
  //   "product-name": "Satin gown",
  //   "price": "€ 3,185",
  //   "availability": "available sizes",
  //   "available-size": "FR 34XXS",
  //   "available-size 2": "FR 36XS-S",
  //   "available-size 3": "FR 38S-M",
  //   "available-size 4": "FR 40M-L",
  //   "available-size 5": "FR 42L-XL",
  //   "available-size 6": "FR 44XL",
  //   "available-size 7": "",
  //   "choose-size": "Please choose your size:",
  //   "available-sizes": "FR 34XXS",
  //   "available-sizes 2": "FR 36XS-S",
  //   "available-sizes 3": "FR 38S-M",
  //   "available-sizes 4": "FR 40M-L",
  //   "product-button 2": "",
  //   "no-sizes": "",
  //   "available-size 8": "",
  //   "available-size 9": "",
  //   "available-size 10": "",
  //   "available-size 11": "",
  //   "available-sizes 9": "",
  //   "available-sizes 10": "",
  //   "available-sizes 11": "",
  //   "lazyload src": "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
  // }
]


//text changing at start of the page*************************
let sentences = ["3 days only: Extra 10% off selected sale", "Enjoy free shipping for a short time only"];
i = 0;
let offer_text = document.querySelector("#offer-text");

function changeText() {
  offer_text.innerHTML = sentences[i % sentences.length];
  i++;

  setTimeout(changeText, 2500);
}
changeText();

//arrow-click hide and show*********************************
let arrow = document.getElementById("arrow");
let pattern_arrow = document.querySelector("#pattern-arrow");
pattern_arrow.style.display = "block"

setInterval(() => {
  if (pattern_arrow.style.display == "block") {
    arrow.addEventListener("click", function () {
      pattern_arrow.style.display = "none"

    })
  }
  else {
    arrow.addEventListener("click", function () {
      pattern_arrow.style.display = "block"
    })
  }
}, 1)

//cards section*******************************************



let cards = document.querySelector(".cards");
function displayData(data) {
     cards.innerHTML="";
    
     data.forEach((item)=>{
      let div1=document.createElement("div");
      let div2=document.createElement("div");
       div2.setAttribute("class","top")
      let hr1=document.createElement("hr");
      let hr2=document.createElement("hr");
      let arrival=document.createElement("span");
      arrival.innerText=item.product_button;
       
      let div3=document.createElement("div");
      div3.setAttribute("class","bottom")
      let image=document.createElement("img");
      image.src=item.image;
      let brand=document.createElement("span")
      brand.innerText="GIVENCHY";
      let title=document.createElement("p")
      title.innerText=item.product_name;
      let price=document.createElement("h6");
      price.innerText=item.price;
      
       div2.append(hr1,arrival,hr2);
       div3.append(image,brand,title,price);
       div1.append(div2,div3)
       cards.append(div1);
     })
     

  // let mapped_data = data.map((item) => {
  //   return ` 
  //           <div class="hello">
  //            <hr>
  //           <div>
  //            <span>${item.product_button}<span>
  //           </div>
  //           <hr>
  //           <div>
  //           <img src="${item.image}"
  //           </div>
  //           </div> 
  //  `
  // })
  // cards.innerHTML=mapped_data.join(" ")

}
displayData(details)










